competencies = [
    ["Skill_0", [("Довузовские компетенции", "ru"), ("Pre-university competencies", "en")], None],
    ["Skill_0.1", [("Русский язык", "ru"), ("Russian language", "en")], "Skill_0"],
    ["Skill_0.2", [("Профильная математика", "ru"), ("Profiled mathematics", "en")], "Skill_0"],
    ["Skill_0.3", [("Информатика и ИКТ", "ru"), ("Informatics and ICT", "en")], "Skill_0"],

    ["Skill_1", [("Универсальные компетенции", "ru"), ("Universal competencies", "en")], None],
    ["Skill_1.1", [("Коммуникативные навыки", "ru"), ("Communication skills", "en")], "Skill_1"],
    ["Skill_1.1.1", [("Устная коммуникация", "ru"), ("Oral communication", "en")], "Skill_1.1"],
    ["Skill_1.1.2", [("Письменная коммуникация", "ru"), ("Written communication", "en")], "Skill_1.1"],
    ["Skill_1.1.3", [("Визуальная коммуникация", "ru"), ("Visual communication", "en")], "Skill_1.1"],
    ["Skill_1.1.4", [("Межкультурная коммуникация", "ru"), ("Intercultural communication", "en")], "Skill_1.1"],
    ["Skill_1.2", [("Профессиональная этика", "ru"), ("Professional ethics", "en")], "Skill_1"],
    ["Skill_1.2.1", [("Ответственность и надежность", "ru"), ("Responsibility and reliability", "en")], "Skill_1.2"],
    ["Skill_1.2.2", [("Конфиденциальность данных", "ru"), ("Data confidentiality", "en")], "Skill_1.2"],
    ["Skill_1.2.3", [("Соблюдение кодекса поведения", "ru"), ("Adherence to the code of conduct", "en")], "Skill_1.2"],
    ["Skill_1.2.4", [("Этика в технологиях", "ru"), ("Ethics in technology", "en")], "Skill_1.2"],
    ["Skill_1.3", [("Креативность и инновации", "ru"), ("Creativity and innovation", "en")], "Skill_1"],
    ["Skill_1.3.1", [("Генерация идей", "ru"), ("Idea generation", "en")], "Skill_1.3"],
    ["Skill_1.3.2", [("Проектирование новых решений", "ru"), ("Designing new solutions", "en")], "Skill_1.3"],
    ["Skill_1.3.3", [("Принятие рискованных решений", "ru"), ("Making risky decisions", "en")], "Skill_1.3"],
    ["Skill_1.3.4", [("Адаптивность и гибкость", "ru"), ("Adaptability and flexibility", "en")], "Skill_1.3"],
    ["Skill_1.4", [("Критическое мышление", "ru"), ("Critical thinking", "en")], "Skill_1"],
    ["Skill_1.4.1", [("Анализ и оценка информации", "ru"), ("Information analysis and assessment", "en")], "Skill_1.4"],
    ["Skill_1.4.2", [("Логическое рассуждение", "ru"), ("Logical reasoning", "en")], "Skill_1.4"],
    ["Skill_1.4.3", [("Решение сложных проблем", "ru"), ("Problem-solving", "en")], "Skill_1.4"],
    ["Skill_1.4.4", [("Принятие взвешенных решений", "ru"), ("Making informed decisions", "en")], "Skill_1.4"],
    # ... (previous elements)
    ["Skill_2", [("Общепрофессиональные компетенции", "ru"), ("General professional competencies", "en")], None],
    ["Skill_2.1", [("Аналитическое мышление", "ru"), ("Analytical thinking", "en")], "Skill_2"],
    ["Skill_2.1.1", [("Логическое мышление", "ru"), ("Logical thinking", "en")], "Skill_2.1"],
    ["Skill_2.1.2", [("Анализ данных", "ru"), ("Data analysis", "en")], "Skill_2.1"],
    ["Skill_2.1.3", [("Структурирование информации", "ru"), ("Information structuring", "en")], "Skill_2.1"],
    ["Skill_2.2", [("Работа в команде", "ru"), ("Teamwork", "en")], "Skill_2"],
    ["Skill_2.2.1", [("Коллаборативное решение задач", "ru"), ("Collaborative problem-solving", "en")], "Skill_2.2"],
    ["Skill_2.2.2", [("Разделение обязанностей", "ru"), ("Task delegation", "en")], "Skill_2.2"],
    ["Skill_2.2.3", [("Эффективное общение в команде", "ru"), ("Effective team communication", "en")], "Skill_2.2"],
    ["Skill_2.2.4", [("Конструктивное разрешение конфликтов", "ru"), ("Constructive conflict resolution", "en")],
     "Skill_2.2"],
    ["Skill_2.3", [("Управление временем", "ru"), ("Time management", "en")], "Skill_2"],
    ["Skill_2.3.1", [("Планирование задач", "ru"), ("Task planning", "en")], "Skill_2.3"],
    ["Skill_2.3.2", [("Приоритизация задач", "ru"), ("Task prioritization", "en")], "Skill_2.3"],
    ["Skill_2.3.3", [("Соблюдение сроков", "ru"), ("Deadline adherence", "en")], "Skill_2.3"],
    ["Skill_2.3.4", [("Управление рабочим временем", "ru"), ("Work time management", "en")], "Skill_2.3"],
    ["Skill_2.4", [("Презентационные навыки", "ru"), ("Presentation skills", "en")], "Skill_2"],
    ["Skill_2.4.1", [("Создание информативных презентаций", "ru"), ("Creating informative presentations", "en")],
     "Skill_2.4"],
    ["Skill_2.4.2", [("Публичное выступление", "ru"), ("Public speaking", "en")], "Skill_2.4"],
    ["Skill_2.4.3", [("Визуализация данных и идей", "ru"), ("Data and idea visualization", "en")], "Skill_2.4"],
    ["Skill_2.4.4", [("Адаптация презентации к аудитории", "ru"), ("Adapting presentations to the audience", "en")],
     "Skill_2.4"],
    ["Skill_2.5", [("Профессиональное обучение", "ru"), ("Professional learning", "en")], "Skill_2"],
    ["Skill_2.5.1", [("Постоянное самообразование", "ru"), ("Continuous self-improvement", "en")], "Skill_2.5"],
    ["Skill_2.5.2", [("Адаптация к новым технологиям", "ru"), ("Adapting to new technologies", "en")], "Skill_2.5"],
    ["Skill_2.5.3", [("Изучение индустриальных стандартов", "ru"), ("Studying industry standards", "en")], "Skill_2.5"],
    ["Skill_2.5.4", [("Эффективные методы обучения", "ru"), ("Effective learning methods", "en")], "Skill_2.5"],
    ["Skill_2.6", [("Межкультурная компетенция", "ru"), ("Cross-cultural competence", "en")], "Skill_2"],
    ["Skill_2.6.1", [("Понимание культурных различий", "ru"), ("Understanding cultural differences", "en")],
     "Skill_2.6"],
    ["Skill_2.6.2", [("Адаптация к межкультурному окружению", "ru"), ("Adapting to multicultural environments", "en")],
     "Skill_2.6"],
    ["Skill_2.6.3", [("Межкультурное коммуницирование", "ru"), ("Cross-cultural communication", "en")], "Skill_2.6"],
    ["Skill_2.6.4", [("Уважение к культурным нормам", "ru"), ("Respect for cultural norms", "en")], "Skill_2.6"],
    # ... (previous elements)
    ["Skill_3", [("Профессиональные компетенции", "ru"), ("Professional competencies", "en")], None],
    ["Skill_3.1", [("Разработка программного кода", "ru"), ("Software development", "en")], "Skill_3"],
    ["Skill_3.1.1", [("Выбор языков программирования", "ru"), ("Programming language selection", "en")], "Skill_3.1"],
    ["Skill_3.1.1.1", [("Знание Python", "ru"), ("Python proficiency", "en")], "Skill_3.1.1"],
    ["Skill_3.1.1.2", [("Знание Java", "ru"), ("Java proficiency", "en")], "Skill_3.1.1"],
    ["Skill_3.1.1.3", [("Знание C++", "ru"), ("C++ proficiency", "en")], "Skill_3.1.1"],
    ["Skill_3.1.1.4", [("Знание JavaScript", "ru"), ("JavaScript proficiency", "en")], "Skill_3.1.1"],
    ["Skill_3.1.2",
     [("ООП и паттерны проектирования", "ru"), ("Object-Oriented Programming and Design Patterns", "en")], "Skill_3.1"],
    ["Skill_3.1.2.1", [("Принципы ООП", "ru"), ("Principles of OOP", "en")], "Skill_3.1.2"],
    ["Skill_3.1.2.2", [("Паттерн Singleton", "ru"), ("Singleton pattern", "en")], "Skill_3.1.2"],
    ["Skill_3.1.2.3", [("Паттерн Factory Method", "ru"), ("Factory Method pattern", "en")], "Skill_3.1.2"],
    ["Skill_3.1.2.4", [("Паттерн Observer", "ru"), ("Observer pattern", "en")], "Skill_3.1.2"],
    ["Skill_3.1.2.5", [("Паттерн MVC", "ru"), ("MVC pattern", "en")], "Skill_3.1.2"],
    ["Skill_3.1.2.6", [("Паттерн MVVM", "ru"), ("MVVM pattern", "en")], "Skill_3.1.2"],
    ["Skill_3.1.3", [("Структуры данных и алгоритмы", "ru"), ("Data Structures and Algorithms", "en")], "Skill_3.1"],
    ["Skill_3.1.3.1", [("Сортировки", "ru"), ("Sorting algorithms", "en")], "Skill_3.1.3"],
    ["Skill_3.1.3.2", [("Поиск", "ru"), ("Searching algorithms", "en")], "Skill_3.1.3"],
    ["Skill_3.1.3.3", [("Сложность алгоритмов", "ru"), ("Algorithm complexity", "en")], "Skill_3.1.3"],
    ["Skill_3.1.3.4", [("Графы и деревья", "ru"), ("Graphs and trees", "en")], "Skill_3.1.3"],
    ["Skill_3.1.3.5", [("Хеш-таблицы", "ru"), ("Hash tables", "en")], "Skill_3.1.3"],
    ["Skill_3.1.3.6", [("Динамическое программирование", "ru"), ("Dynamic programming", "en")], "Skill_3.1.3"],
    ["Skill_3.1.4", [("Тестирование и отладка", "ru"), ("Testing and debugging", "en")], "Skill_3.1"],
    ["Skill_3.1.4.1", [("Unit-тестирование", "ru"), ("Unit testing", "en")], "Skill_3.1.4"],
    ["Skill_3.1.4.2", [("Интеграционное тестирование", "ru"), ("Integration testing", "en")], "Skill_3.1.4"],
    ["Skill_3.1.4.3", [("Отладка и профилирование", "ru"), ("Debugging and profiling", "en")], "Skill_3.1.4"],
    ["Skill_3.1.4.4", [("Тестирование безопасности", "ru"), ("Security testing", "en")], "Skill_3.1.4"],
    ["Skill_3.1.4.5", [("Тестирование производительности", "ru"), ("Performance testing", "en")], "Skill_3.1.4"],
    # ... (previous elements)
    ["Skill_3.2", [("Разработка веб-приложений", "ru"), ("Web Application Development", "en")], "Skill_3"],
    ["Skill_3.2.1", [("Фронтенд разработка", "ru"), ("Frontend Development", "en")], "Skill_3.2"],
    ["Skill_3.2.1.1", [("HTML и CSS", "ru"), ("HTML and CSS", "en")], "Skill_3.2.1"],
    ["Skill_3.2.1.2", [("JavaScript", "ru"), ("JavaScript", "en")], "Skill_3.2.1"],
    ["Skill_3.2.1.3", [("Фреймворки для фронтенда", "ru"), ("Frontend Frameworks", "en")], "Skill_3.2.1"],
    ["Skill_3.2.1.4", [("Адаптивный дизайн", "ru"), ("Responsive Design", "en")], "Skill_3.2.1"],
    ["Skill_3.2.1.5", [("Интерфейсы и пользовательский опыт", "ru"), ("User Interfaces and User Experience", "en")],
     "Skill_3.2.1"],
    ["Skill_3.2.2", [("Бекенд разработка", "ru"), ("Backend Development", "en")], "Skill_3.2"],
    ["Skill_3.2.2.1", [("Фреймворки для бекенда", "ru"), ("Backend Frameworks", "en")], "Skill_3.2.2"],
    ["Skill_3.2.2.2", [("RESTful API", "ru"), ("RESTful API", "en")], "Skill_3.2.2"],
    ["Skill_3.2.2.3", [("Базы данных", "ru"), ("Databases", "en")], "Skill_3.2.2"],
    ["Skill_3.2.2.4", [("ORM", "ру"), ("Object-Relational Mapping (ORM)", "en")], "Skill_3.2.2"],
    ["Skill_3.2.2.5", [("Миграции данных", "ru"), ("Data Migrations", "en")], "Skill_3.2.2"],
    ["Skill_3.2.2.6", [("NoSQL базы данных", "ru"), ("NoSQL Databases", "en")], "Skill_3.2.2"],
    # ... (previous elements)
    ["Skill_3.3", [("Информационная безопасность", "ru"), ("Information Security", "en")], "Skill_3"],
    ["Skill_3.3.1", [("Основы криптографии", "ru"), ("Cryptography Basics", "en")], "Skill_3.3"],
    ["Skill_3.3.1.1", [("Симметричное шифрование", "ru"), ("Symmetric Encryption", "en")], "Skill_3.3.1"],
    ["Skill_3.3.1.2", [("Асимметричное шифрование", "ru"), ("Asymmetric Encryption", "en")], "Skill_3.3.1"],
    ["Skill_3.3.1.3", [("Цифровые подписи", "ru"), ("Digital Signatures", "en")], "Skill_3.3.1"],
    ["Skill_3.3.2", [("Защита данных и аутентификация", "ru"), ("Data Protection and Authentication", "en")],
     "Skill_3.3"],
    ["Skill_3.3.2.1", [("Хэширование и соли", "ru"), ("Hashing and Salting", "en")], "Skill_3.3.2"],
    ["Skill_3.3.2.2", [("JWT токены", "ru"), ("JWT Tokens", "en")], "Skill_3.3.2"],
    ["Skill_3.3.2.3", [("OAuth и OpenID Connect", "ru"), ("OAuth and OpenID Connect", "en")], "Skill_3.3.2"],
    ["Skill_3.3.3", [("Сетевая безопасность", "ru"), ("Network Security", "en")], "Skill_3.3"],
    ["Skill_3.3.3.1", [("Firewall и IDS/IPS", "ru"), ("Firewall and IDS/IPS", "en")], "Skill_3.3.3"],
    ["Skill_3.3.3.2", [("VPN и шифрование трафика", "ru"), ("VPN and Traffic Encryption", "en")], "Skill_3.3.3"],
    ["Skill_3.3.3.3", [("DDoS защита", "ru"), ("DDoS Protection", "en")], "Skill_3.3.3"],
    # ... (previous elements)
    ["Skill_3.4", [("Архитектура информационных систем", "ru"), ("Information Systems Architecture", "en")], "Skill_3"],
    ["Skill_3.4.1", [("Монолитная архитектура", "ru"), ("Monolithic Architecture", "en")], "Skill_3.4"],
    ["Skill_3.4.1.1", [("Монолитное приложение", "ru"), ("Monolithic Application", "en")], "Skill_3.4.1"],
    ["Skill_3.4.1.2", [("Монолитное развертывание", "ru"), ("Monolithic Deployment", "en")], "Skill_3.4.1"],
    ["Skill_3.4.1.3", [("Монолитное масштабирование", "ru"), ("Monolithic Scaling", "en")], "Skill_3.4.1"],
    ["Skill_3.4.1.4", [("Монолитный мониторинг", "ru"), ("Monolithic Monitoring", "en")], "Skill_3.4.1"],
    ["Skill_3.4.2", [("Микросервисная архитектура", "ru"), ("Microservices Architecture", "en")], "Skill_3.4"],
    ["Skill_3.4.2.1", [("Микросервисное развертывание", "ru"), ("Microservices Deployment", "en")], "Skill_3.4.2"],
    ["Skill_3.4.2.2", [("Микросервисный мониторинг", "ru"), ("Microservices Monitoring", "en")], "Skill_3.4.2"],
    ["Skill_3.4.2.3", [("Микросервисное масштабирование", "ru"), ("Microservices Scaling", "en")], "Skill_3.4.2"],
    ["Skill_3.4.2.4", [("Микросервисные шаблоны", "ru"), ("Microservices Patterns", "en")], "Skill_3.4.2"],
    ["Skill_3.4.3", [("Событийно-ориентированная архитектура", "ru"), ("Event-Driven Architecture", "en")],
     "Skill_3.4"],
    ["Skill_3.4.3.1", [("Паттерны обработки событий", "ru"), ("Event Processing Patterns", "en")], "Skill_3.4.3"],
    ["Skill_3.4.3.2", [("Системы потоковой обработки", "ru"), ("Stream Processing Systems", "en")], "Skill_3.4.3"],
    ["Skill_3.4.3.3", [("Событийная маршрутизация", "ru"), ("Event Routing", "en")], "Skill_3.4.3"],
    ["Skill_3.4.3.4", [("Компенсирующие транзакции", "ru"), ("Compensating Transactions", "en")], "Skill_3.4.3"],
    # ... (previous elements)
    ["Skill_3.5", [("Управление проектами", "ru"), ("Project Management", "en")], "Skill_3"],
    ["Skill_3.5.1", [("Планирование и оценка", "ru"), ("Planning and Estimation", "en")], "Skill_3.5"],
    ["Skill_3.5.1.1", [("Составление плана проекта", "ru"), ("Project Planning", "en")], "Skill_3.5.1"],
    ["Skill_3.5.1.2", [("Оценка рисков и ресурсов", "ru"), ("Risk and Resource Assessment", "en")], "Skill_3.5.1"],
    ["Skill_3.5.1.3", [("Графики Гантта и диаграммы Перта", "ru"), ("Gantt Charts and Pert Diagrams", "en")],
     "Skill_3.5.1"],
    ["Skill_3.5.1.4", [("Оценка сложности задач", "ru"), ("Task Complexity Assessment", "en")], "Skill_3.5.1"],
    ["Skill_3.5.2", [("Управление рисками", "ru"), ("Risk Management", "en")], "Skill_3.5"],
    ["Skill_3.5.2.1", [("Идентификация рисков", "ru"), ("Risk Identification", "en")], "Skill_3.5.2"],
    ["Skill_3.5.2.2", [("Анализ и приоритизация рисков", "ru"), ("Risk Analysis and Prioritization", "en")],
     "Skill_3.5.2"],
    ["Skill_3.5.2.3", [("Планирование мер по снижению рисков", "ru"), ("Risk Mitigation Planning", "en")],
     "Skill_3.5.2"],
    ["Skill_3.5.2.4", [("Мониторинг и контроль рисков", "ru"), ("Risk Monitoring and Control", "en")], "Skill_3.5.2"],
    ["Skill_3.5.3", [("Методологии разработки", "ru"), ("Development Methodologies", "en")], "Skill_3.5"],
    ["Skill_3.5.3.1", [("Agile методологии", "ru"), ("Agile Methodologies", "en")], "Skill_3.5.3"],
    ["Skill_3.5.3.2", [("Waterfall методология", "ru"), ("Waterfall Methodology", "en")], "Skill_3.5.3"],
    ["Skill_3.5.3.3", [("Scrum фреймворк", "ru"), ("Scrum Framework", "en")], "Skill_3.5.3"],
    ["Skill_3.5.3.4", [("Kanban методология", "ru"), ("Kanban Methodology", "en")], "Skill_3.5.3"],
    # ... (previous elements)
    ["Skill_3.6",
     [("Искусственный интеллект и машинное обучение", "ru"), ("Artificial Intelligence and Machine Learning", "en")],
     "Skill_3"],
    ["Skill_3.6.1", [("Основы машинного обучения", "ru"), ("Fundamentals of Machine Learning", "en")], "Skill_3.6"],
    ["Skill_3.6.1.1", [("Типы задач машинного обучения", "ru"), ("Types of Machine Learning Tasks", "en")],
     "Skill_3.6.1"],
    ["Skill_3.6.1.2", [("Обучение с учителем и без учителя", "ru"), ("Supervised and Unsupervised Learning", "en")],
     "Skill_3.6.1"],
    ["Skill_3.6.1.3", [("Кросс-валидация и выбор модели", "ru"), ("Cross-Validation and Model Selection", "en")],
     "Skill_3.6.1"],
    ["Skill_3.6.1.4", [("Оценка и интерпретация моделей", "ru"), ("Model Evaluation and Interpretation", "en")],
     "Skill_3.6.1"],
    ["Skill_3.6.2", [("Глубокое обучение и нейронные сети", "ru"), ("Deep Learning and Neural Networks", "en")],
     "Skill_3.6"],
    ["Skill_3.6.2.1", [("Искусственные нейронные сети", "ru"), ("Artificial Neural Networks", "en")], "Skill_3.6.2"],
    ["Skill_3.6.2.2", [("Сверточные нейронные сети", "ru"), ("Convolutional Neural Networks", "en")], "Skill_3.6.2"],
    ["Skill_3.6.2.3", [("Рекуррентные нейронные сети", "ru"), ("Recurrent Neural Networks", "en")], "Skill_3.6.2"],
    ["Skill_3.6.2.4", [("Генеративные нейронные сети", "ru"), ("Generative Neural Networks", "en")], "Skill_3.6.2"],
    ["Skill_3.6.3", [("Обработка естественного языка", "ru"), ("Natural Language Processing", "en")], "Skill_3.6"],
    ["Skill_3.6.3.1", [("Токенизация и стемминг", "ru"), ("Tokenization and Stemming", "en")], "Skill_3.6.3"],
    ["Skill_3.6.3.2", [("Извлечение информации", "ru"), ("Information Extraction", "en")], "Skill_3.6.3"],
    ["Skill_3.6.3.3", [("Сентимент анализ", "ru"), ("Sentiment Analysis", "en")], "Skill_3.6.3"],
    ["Skill_3.6.3.4", [("Машинный перевод", "ru"), ("Machine Translation", "en")], "Skill_3.6.3"],
    ["Skill_3.7", [("Развертывание и обслуживание", "ru"), ("Deployment and Maintenance", "en")], "Skill_3"],
    ["Skill_3.7.1", [("DevOps практики", "ru"), ("DevOps Practices", "en")], "Skill_3.7"],
    ["Skill_3.7.1.1", [("Концепция DevOps", "ru"), ("DevOps Concept", "en")], "Skill_3.7.1"],
    ["Skill_3.7.1.2", [("Инфраструктура как код", "ru"), ("Infrastructure as Code", "en")], "Skill_3.7.1"],
    ["Skill_3.7.1.3", [("Непрерывная интеграция и доставка", "ru"), ("Continuous Integration and Delivery", "en")],
     "Skill_3.7.1"],
    ["Skill_3.7.1.4", [("Автоматизация развертывания", "ru"), ("Deployment Automation", "en")], "Skill_3.7.1"],
    ["Skill_3.7.2", [("Контейнеризация и оркестрация", "ru"), ("Containerization and Orchestration", "en")],
     "Skill_3.7"],
    ["Skill_3.7.2.1", [("Docker контейнеры", "ru"), ("Docker Containers", "en")], "Skill_3.7.2"],
    ["Skill_3.7.2.2", [("Kubernetes оркестратор", "ru"), ("Kubernetes Orchestrator", "en")], "Skill_3.7.2"],
    ["Skill_3.7.2.3", [("Масштабирование и балансировка нагрузки", "ru"), ("Scaling and Load Balancing", "en")],
     "Skill_3.7.2"],
    ["Skill_3.7.2.4", [("Мониторинг и журналирование", "ru"), ("Monitoring and Logging", "en")], "Skill_3.7.2"],
    # ... (previous elements)
    ["Skill_3.7.3", [("Облачные платформы", "ru"), ("Cloud Platforms", "en")], "Skill_3.7"],
    ["Skill_3.7.3.1", [("Amazon Web Services (AWS)", "ru"), ("Amazon Web Services (AWS)", "en")], "Skill_3.7.3"],
    ["Skill_3.7.3.2", [("Microsoft Azure", "ru"), ("Microsoft Azure", "en")], "Skill_3.7.3"],
    ["Skill_3.7.3.3", [("Google Cloud Platform (GCP)", "ru"), ("Google Cloud Platform (GCP)", "en")], "Skill_3.7.3"],
    ["Skill_3.7.3.4", [("Serverless архитектура", "ru"), ("Serverless Architecture", "en")], "Skill_3.7.3"]
]

dependencies = [
    ("Skill_2.2", "Skill_1.2"),
    ("Skill_2.3", "Skill_1.3"),
    ("Skill_2.4", "Skill_1.4"),
    ("Skill_3.1", "Skill_2.1"),
    ("Skill_3.3.2", "Skill_2.3.2"),
    ("Skill_3.5.2", "Skill_2.5.2"),
    ("Skill_3.5.3", "Skill_2.5.3"),
    ("Skill_3.6.3", "Skill_3.5.3"),
    ("Skill_3.7.1.1", "Skill_3.6.1"),
    ("Skill_3.7.2.1", "Skill_3.7.1.1"),
    ("Skill_3.7.2.2", "Skill_3.7.1.2"),
    ("Skill_3.7.2.3", "Skill_3.7.1.3"),
    ("Skill_3.7.2.4", "Skill_3.7.1.4"),
    ("Skill_3.7.3.1", "Skill_3.7.2.2"),
    ("Skill_3.7.3.2", "Skill_3.7.2.3"),
    ("Skill_3.7.3.3", "Skill_3.7.2.4"),
    ("Skill_1.2", "Skill_1.1"),
    ("Skill_1.3", "Skill_1.2"),
    ("Skill_1.4", "Skill_1.3"),
    ("Skill_2.1", "Skill_1.1"),
    ("Skill_2.2.1", "Skill_2.1"),
    ("Skill_2.2.2", "Skill_2.2.1"),
    ("Skill_2.2.3", "Skill_2.2.2"),
    ("Skill_2.3.1", "Skill_2.2.1"),
    ("Skill_2.3.2", "Skill_2.2.2"),
    ("Skill_2.3.3", "Skill_2.2.3"),
    ("Skill_2.4", "Skill_2.1"),
    ("Skill_2.5.1", "Skill_2.1"),
    ("Skill_2.5.2", "Skill_2.2.1"),
    ("Skill_3.1", "Skill_3.6.1"),
    ("Skill_3.2.1", "Skill_3.1"),
    ("Skill_3.3.2", "Skill_3.2.2"),
    ("Skill_3.4", "Skill_3.1"),
    ("Skill_3.5.3", "Skill_3.2.2"),
    ("Skill_3.6.1", "Skill_3.1"),
    ("Skill_3.6.3", "Skill_3.2.2"),
    ("Skill_3.7.1.2", "Skill_3.6.2"),
    ("Skill_3.7.2.1", "Skill_3.7.1.1"),
    ("Skill_3.7.2.2", "Skill_3.7.1.2"),
    ("Skill_3.7.2.3", "Skill_3.7.1.3"),
    ("Skill_3.7.2.4", "Skill_3.7.1.4"),
    ("Skill_3.7.3.1", "Skill_3.7.2.2"),
    ("Skill_3.7.3.2", "Skill_3.7.2.3"),
    ("Skill_3.7.3.3", "Skill_3.7.2.4"),
    ("Skill_3.1.1.2", "Skill_3.1.3"),
]

courses = [
    ("Course_00", [("Подготовительный курс", "ru"), ("Preparatory Course", "en")], 3, [("Зачет", "ru"), ("Test", "en")], "Semester_0"),
    ("Course_01", [("Введение в программирование", "ru"), ("Introduction to Programming", "en")], 5, [("Экзамен", "ru"), ("Exam", "en")], "Semester_1"),
    ("Course_02", [("Основы алгоритмизации", "ru"), ("Fundamentals of Algorithmization", "en")], 5, [("Экзамен", "ru"), ("Exam", "en")], "Semester_1"),
    ("Course_03", [("Дискретная математика", "ru"), ("Discrete Mathematics", "en")], 5, [("Экзамен", "ru"), ("Exam", "en")], "Semester_1"),
    ("Course_04", [("Основы программирования на Python", "ru"), ("Fundamentals of Python Programming", "en")], 6, [("Экзамен", "ru"), ("Exam", "en")], "Semester_2"),
    ("Course_05", [("Структуры данных и алгоритмы", "ru"), ("Data Structures and Algorithms", "en")], 6, [("Экзамен", "ru"), ("Exam", "en")], "Semester_2"),
    ("Course_06", [("Архитектура компьютерных систем", "ru"), ("Computer Systems Architecture", "en")], 4, [("Экзамен", "ru"), ("Exam", "en")], "Semester_2"),
    ("Course_07", [("Операционные системы", "ru"), ("Operating Systems", "en")], 4, [("Экзамен", "ru"), ("Exam", "en")], "Semester_3"),
    ("Course_08", [("Базы данных и SQL", "ru"), ("Databases and SQL", "en")], 5, [("Экзамен", "ru"), ("Exam", "en")], "Semester_3"),
    ("Course_09", [("Веб-разработка и HTML/CSS", "ru"), ("Web Development and HTML/CSS", "en")], 5, [("Экзамен", "ru"), ("Exam", "en")], "Semester_3"),
    ("Course_10", [("Программирование на Java", "ru"), ("Java Programming", "en")], 6, [("Экзамен", "ru"), ("Exam", "en")], "Semester_4"),
    ("Course_11", [("Математическая логика и теория алгоритмов", "ru"), ("Mathematical Logic and Algorithm Theory", "en")], 5, [("Экзамен", "ru"), ("Exam", "en")], "Semester_4"),
    ("Course_12", [("Проектирование информационных систем", "ru"), ("Information Systems Design", "en")], 6, [("Экзамен", "ru"), ("Exam", "en")], "Semester_4"),
    ("Course_13", [("Мобильная разработка", "ru"), ("Mobile Development", "en")], 5, [("Экзамен", "ru"), ("Exam", "en")], "Semester_5"),
    ("Course_14", [("Сети и протоколы", "ru"), ("Networks and Protocols", "en")], 5, [("Экзамен", "ru"), ("Exam", "en")], "Semester_5"),
    ("Course_15", [("Тестирование программного обеспечения", "ru"), ("Software Testing", "en")], 4, [("Экзамен", "ru"), ("Exam", "en")], "Semester_5"),
    ("Course_16", [("Машинное обучение и искусственный интеллект", "ru"), ("Machine Learning and Artificial Intelligence", "en")], 6, [("Экзамен", "ru"), ("Exam", "en")], "Semester_6"),
    ("Course_17", [("Безопасность информационных систем", "ru"), ("Information Systems Security", "en")], 4, [("Экзамен", "ru"), ("Exam", "en")], "Semester_6"),
    ("Course_18", [("Проектная работа по программированию", "ru"), ("Programming Project Work", "en")], 7, [("Зачет", "ru"), ("Test", "en")], "Semester_6"),
    ("Course_19", [("Интернет вещей и умный город", "ru"), ("Internet of Things and Smart Cities", "en")], 4, [("Зачет", "ru"), ("Test", "en")], "Semester_7"),
    ("Course_20", [("Компьютерная графика и визуализация", "ru"), ("Computer Graphics and Visualization", "en")], 5, [("Зачет", "ru"), ("Test", "en")], "Semester_7"),
    ("Course_21", [("Управление IT-проектами", "ru"), ("IT Project Management", "en")], 4, [("Зачет", "ru"), ("Test", "en")], "Semester_7"),
    ("Course_22", [("Анализ данных", "ru"), ("Data Analysis", "en")], 5, [("Зачет", "ru"), ("Test", "en")], "Semester_8"),
    ("Course_23", [("Этика и профессиональные стандарты", "ru"), ("Ethics and Professional Standards", "en")], 3, [("Зачет", "ru"), ("Test", "en")], "Semester_8"),
    ("Course_24", [("Теория вероятностей и математическая статистика", "ru"), ("Probability Theory and Mathematical Statistics", "en")], 5, [("Экзамен", "ru"), ("Exam", "en")], "Semester_8"),
    ("Course_25", [("Функциональное программирование", "ru"), ("Functional Programming", "en")], 4, [("Экзамен", "ru"), ("Exam", "en")], "Semester_1"),
    ("Course_26", [("Распределенные системы", "ru"), ("Distributed Systems", "en")], 5, [("Экзамен", "ru"), ("Exam", "en")], "Semester_2"),
    ("Course_27", [("Разработка интерфейсов", "ru"), ("Interface Development", "en")], 4, [("Зачет", "ru"), ("Test", "en")], "Semester_3"),
    ("Course_28", [("Администрирование баз данных", "ru"), ("Database Administration", "en")], 5, [("Зачет", "ru"), ("Test", "en")], "Semester_4"),
    ("Course_29", [("Технологии виртуализации", "ru"), ("Virtualization Technologies", "en")], 4, [("Экзамен", "ru"), ("Exam", "en")], "Semester_5"),
    ("Course_30", [("Системное программирование", "ru"), ("Systems Programming", "en")], 5, [("Экзамен", "ru"), ("Exam", "en")], "Semester_6"),
    ("Course_31", [("Английский язык для программистов", "ru"), ("English for Programmers", "en")], 3, [("Зачет", "ru"), ("Test", "en")], "Semester_7"),
    ("Course_32", [("Программирование на C++", "ru"), ("C++ Programming", "en")], 6, [("Экзамен", "ru"), ("Exam", "en")], "Semester_8"),
    ("Course_33", [("Компьютерные системы и сети", "ru"), ("Computer Systems and Networks", "en")], 4, [("Экзамен", "ru"), ("Exam", "en")], "Semester_1"),
    ("Course_34", [("Моделирование и анализ систем", "ru"), ("Modeling and Analysis of Systems", "en")], 5, [("Экзамен", "ru"), ("Exam", "en")], "Semester_2"),
    ("Course_37", [("Информационные технологии в бизнесе", "ru"), ("Information Technology in Business", "en")], 4, [("Зачет", "ru"), ("Test", "en")], "Semester_6"),
    ("Course_38", [("Разработка мобильных приложений", "ru"), ("Mobile App Development", "en")], 5, [("Экзамен", "ru"), ("Exam", "en")], "Semester_7"),
    ("Course_39", [("Основы криптографии", "ru"), ("Fundamentals of Cryptography", "en")], 4, [("Экзамен", "ru"), ("Exam", "en")], "Semester_1"),
    ("Course_40", [("Производственная практика", "ru"), ("Industrial Practice", "en")], 3, [("Зачет", "ru"), ("Test", "en")], "Semester_3"),
    ("Course_41", [("Сетевая безопасность", "ru"), ("Network Security", "en")], 5, [("Экзамен", "ru"), ("Exam", "en")], "Semester_6"),
    ("Course_42", [("Программирование веб-сервисов", "ru"), ("Web Service Programming", "en")], 4, [("Экзамен", "ru"), ("Exam", "en")], "Semester_7"),
    ("Course_43", [("Физическая культура", "ru"), ("Physical Education", "en")], 2, [("Зачет", "ru"), ("Test", "en")], "Semester_1"),
    ("Course_44", [("Экономика и управление проектами", "ru"), ("Economics and Project Management", "en")], 4, [("Зачет", "ru"), ("Test", "en")], "Semester_2"),
]

discipline_competency_mapping = [
    ("Course_00", "Skill_0"),
    ("Course_00", "Skill_1.1"),
    ("Course_01", "Skill_3.1.1.3"),
    ("Course_01", "Skill_3.1.1.1"),
    ("Course_02", "Skill_3.1.3"),
    ("Course_03", "Skill_2.1"),
    ("Course_04", "Skill_3.1.1.1"),
    ("Course_05", "Skill_3.1.3"),
    ("Course_06", "Skill_3.4"),
    ("Course_07", "Skill_3.7.3"),
    ("Course_08", "Skill_3.2.2.3"),
    ("Course_08", "Skill_3.2.2.4"),
    ("Course_08", "Skill_3.2.2.5"),
    ("Course_08", "Skill_3.2.2.6"),
    ("Course_09", "Skill_3.2.1.1"),
    ("Course_09", "Skill_3.2.1.2"),
    ("Course_10", "Skill_3.1.1.2"),
    ("Course_11", "Skill_3.1.3.3"),
    ("Course_12", "Skill_3.4.1"),
    ("Course_13", "Skill_3.1.1.2"),
    ("Course_14", "Skill_3.3.3.1"),
    ("Course_14", "Skill_3.3.3.2"),
    ("Course_14", "Skill_3.3.3.3"),
    ("Course_15", "Skill_3.1.4.1"),
    ("Course_15", "Skill_3.1.4.2"),
    ("Course_16", "Skill_3.6.1"),
    ("Course_17", "Skill_3.3.2"),
    ("Course_18", "Skill_3.1.2"),
    ("Course_19", "Skill_3.7.3"),
    ("Course_20", "Skill_3.1.3.4"),
    ("Course_21", "Skill_3.5.1"),
    ("Course_21", "Skill_3.5.2"),
    ("Course_21", "Skill_3.5.3"),
    ("Course_22", "Skill_3.6.1"),
    ("Course_23", "Skill_2.6"),
    ("Course_24", "Skill_3.1.3.1"),
    ("Course_25", "Skill_3.1.3.4"),
    ("Course_26", "Skill_3.4.2"),
    ("Course_27", "Skill_3.2.1"),
    ("Course_28", "Skill_3.2.2.3"),
    ("Course_28", "Skill_3.2.2.4"),
    ("Course_29", "Skill_3.7.2"),
    ("Course_30", "Skill_3.4.3"),
    ("Course_31", "Skill_2.6"),
    ("Course_32", "Skill_3.1.1.3"),
    ("Course_33", "Skill_3.3.3.2"),
    ("Course_34", "Skill_3.5.1"),
    ("Course_37", "Skill_2.6.1"),
    ("Course_38", "Skill_2.6.2"),
    ("Course_39", "Skill_2.6.3"),
    ("Course_40", "Skill_3.4.2"),
    ("Course_39", "Skill_3.3.3.2"),
    ("Course_39", "Skill_3.3.1"),
    ("Course_39", "Skill_3.1.1"),
    ("Course_40", "Skill_2.5"),
    ("Course_44", "Skill_2.3.1"),
    ("Course_41", "Skill_3.1.2"),
    ("Course_42", "Skill_3.1.2"),
    ("Course_43", "Skill_1.1"),
]

